cache:
  directories:
  - "$HOME/.pub-cache"
jobs:
  include:
  - stage: test
    os: linux
    language: generic
    addons:
      apt:
        sources:
        - ubuntu-toolchain-r-test
        packages:
        # Flutter依赖
        - libstdc++6
        - fonts-droid
    before_script:
    - git clone https://github.com/flutter/flutter.git -b beta --depth 1
    script:
    - "./flutter/bin/flutter upgrade"
    - "./flutter/bin/flutter test"
 - stage: deployAPK
    os: linux
    language: android
    licenses:
    - android-sdk-preview-license-.+
    - android-sdk-license-.+
    - google-gdk-license-.+
    android:
      components:
      - tools
      - platform-tools
      - build-tools-27.0.3
      - android-27
      - sys-img-armeabi-v7a-google_apis-25
      - extra-android-m2repository
      - extra-google-m2repository
      - extra-google-android-support
    jdk: oraclejdk8
    # 以上都是在安装AndroidSDK
    env: APK_OUTPUT=build/app/outputs/apk/release/app-release.apk
    addons:
      apt:
        sources:
        - ubuntu-toolchain-r-test
        packages:
        - libstdc++6
        - fonts-droid
    #以上为Flutter环境搭建
    before_script:
    # 用你自己的解密命令替代
    - openssl aes-256-cbc -K $encrypted_b4b78a19c009_key -iv $encrypted_b4b78a19c009_iv -in key.properties.enc -out android/key.properties -d
    - openssl aes-256-cbc -K $encrypted_b4b78a19c009_key -iv $encrypted_b4b78a19c009_iv -in key.jks.enc -out android/key.jks -d
    - git clone https://github.com/flutter/flutter.git -b beta --depth 1
    script:
    - "./flutter/bin/flutter upgrade"
    - "./flutter/bin/flutter -v build apk --release"
    deploy:
      provider: releases
      skip_cleanup: true
      # 用你的api_key替代
      api_key:
        secure: 247f613f57ff41f8f8a476004da66186f6587a8e
      file: $APK_OUTPUT
      on:
        tags: true
